import { neon } from "@neondatabase/serverless";
import { buscarOficial2026 } from "../../../../lib/oficialidad-2026";
export const runtime="nodejs";export const dynamic="force-dynamic";
const db=()=>process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null;const vd=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||"");const vc=v=>/^\d{1,6}$/.test(v||"");
function sameOrigin(r){const o=r.headers.get("origin");if(!o)return false;try{return new URL(o).host===r.headers.get("host")}catch{return false}}
async function schema(sql){await sql`CREATE TABLE IF NOT EXISTS guardia_semanas(id bigserial PRIMARY KEY,fecha_inicio date NOT NULL,fecha_fin date NOT NULL,apertura timestamptz NOT NULL,cierre timestamptz NOT NULL,estado text NOT NULL DEFAULT 'abierta',creado_por varchar(6) NOT NULL,creado_en timestamptz NOT NULL DEFAULT now(),actualizado_en timestamptz NOT NULL DEFAULT now(),UNIQUE(fecha_inicio,fecha_fin))`}
export async function GET(r){const sql=db();if(!sql)return Response.json({error:"database_not_configured"},{status:503});const u=new URL(r.url),desde=u.searchParams.get("desde"),hasta=u.searchParams.get("hasta");if(!vd(desde)||!vd(hasta)||desde>hasta)return Response.json({error:"invalid_range"},{status:400});try{await schema(sql);const rows=await sql`SELECT id,fecha_inicio::text,fecha_fin::text,apertura,cierre,estado,creado_por::text,creado_en,actualizado_en FROM guardia_semanas WHERE fecha_inicio<=${hasta}::date AND fecha_fin>=${desde}::date ORDER BY fecha_inicio`;return Response.json({semanas:rows},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return Response.json({error:"database_error"},{status:500})}}
export async function POST(r){if(!sameOrigin(r))return Response.json({error:"forbidden_origin"},{status:403});const sql=db();if(!sql)return Response.json({error:"database_not_configured"},{status:503});let b;try{b=await r.json()}catch{return Response.json({error:"invalid_json"},{status:400})}const inicio=String(b.fechaInicio||""),fin=String(b.fechaFin||""),apertura=String(b.apertura||""),cierre=String(b.cierre||""),oficial=String(b.oficial||"");if(!vd(inicio)||!vd(fin)||inicio>fin||!vc(oficial)||!buscarOficial2026(oficial)||!apertura||!cierre)return Response.json({error:"invalid_data"},{status:400});const a=new Date(apertura),c=new Date(cierre);if(Number.isNaN(+a)||Number.isNaN(+c)||a>=c)return Response.json({error:"invalid_window"},{status:400});try{await schema(sql);await sql`INSERT INTO guardia_semanas(fecha_inicio,fecha_fin,apertura,cierre,estado,creado_por) VALUES(${inicio}::date,${fin}::date,${a.toISOString()}::timestamptz,${c.toISOString()}::timestamptz,'abierta',${oficial}) ON CONFLICT(fecha_inicio,fecha_fin) DO UPDATE SET apertura=EXCLUDED.apertura,cierre=EXCLUDED.cierre,estado='abierta',creado_por=EXCLUDED.creado_por,actualizado_en=now()`;return Response.json({ok:true,fechaInicio:inicio,fechaFin:fin,estado:"abierta"})}catch(e){console.error(e);return Response.json({error:"database_error"},{status:500})}}
export async function PATCH(r){if(!sameOrigin(r))return Response.json({error:"forbidden_origin"},{status:403});const sql=db();if(!sql)return Response.json({error:"database_not_configured"},{status:503});let b;try{b=await r.json()}catch{return Response.json({error:"invalid_json"},{status:400})}const inicio=String(b.fechaInicio||""),fin=String(b.fechaFin||""),estado=String(b.estado||""),oficial=String(b.oficial||"");if(!vd(inicio)||!vd(fin)||!['abierta','cerrada','suspendida','odd_emitida'].includes(estado)||!buscarOficial2026(oficial))return Response.json({error:"invalid_data"},{status:400});try{await schema(sql);const rows=await sql`UPDATE guardia_semanas SET estado=${estado},actualizado_en=now() WHERE fecha_inicio=${inicio}::date AND fecha_fin=${fin}::date RETURNING id`;if(!rows.length)return Response.json({error:"not_found"},{status:404});return Response.json({ok:true,estado})}catch(e){console.error(e);return Response.json({error:"database_error"},{status:500})}}
