import { neon } from "@neondatabase/serverless";
import { NOMINA_2026 } from "../../../../lib/quinta-data";
import { buscarOficial2026 } from "../../../../lib/oficialidad-2026";
export const runtime="nodejs";export const dynamic="force-dynamic";
const vd=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||"");const vc=v=>/^\d{1,6}$/.test(v||"");const db=()=>process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null;
function origin(r){const o=r.headers.get("origin");if(!o)return false;try{return new URL(o).host===r.headers.get("host")}catch{return false}}
async function schema(sql){await sql`CREATE TABLE IF NOT EXISTS guardia_conductores(id bigserial PRIMARY KEY,fecha date NOT NULL UNIQUE,codigo varchar(6) NOT NULL,nombre text NOT NULL,autorizado_por varchar(6) NOT NULL,actualizado_en timestamptz NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS guardia_conductores_autorizados(codigo varchar(6) PRIMARY KEY,nombre text NOT NULL,agregado_por varchar(6) NOT NULL,creado_en timestamptz NOT NULL DEFAULT now())`}
export async function GET(r){const sql=db();if(!sql)return Response.json({error:"database_not_configured"},{status:503});const fecha=new URL(r.url).searchParams.get("fecha");if(!vd(fecha))return Response.json({error:"invalid_date"},{status:400});try{await schema(sql);const x=await sql`SELECT codigo::text,nombre,autorizado_por::text,actualizado_en FROM guardia_conductores WHERE fecha=${fecha}::date LIMIT 1`;return Response.json({fecha,conductor:x[0]||null},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error(e);return Response.json({error:"database_error"},{status:500})}}
export async function POST(r){if(!origin(r))return Response.json({error:"forbidden_origin"},{status:403});const sql=db();if(!sql)return Response.json({error:"database_not_configured"},{status:503});let b;try{b=await r.json()}catch{return Response.json({error:"invalid_json"},{status:400})}const fecha=String(b.fecha||""),codigo=String(b.codigo||""),aut=String(b.autorizadoPor||"");if(!vd(fecha)||!vc(codigo)||!vc(aut))return Response.json({error:"invalid_data"},{status:400});const of=buscarOficial2026(aut),nombre=NOMINA_2026[codigo];if(!of)return Response.json({error:"official_not_authorized"},{status:403});if(!nombre)return Response.json({error:"not_in_roster"},{status:409});try{await schema(sql);const autorizados=await sql`SELECT codigo::text FROM guardia_conductores_autorizados WHERE codigo=${codigo} LIMIT 1`;if(!autorizados.length)return Response.json({error:"driver_not_authorized"},{status:403});const efectivos=await sql`SELECT COALESCE(gr.codigo_reemplazo,gi.codigo)::text codigo FROM guardia_inscripciones gi LEFT JOIN guardia_reemplazos gr ON gr.fecha=gi.fecha AND gr.codigo_original=gi.codigo WHERE gi.fecha=${fecha}::date`;if(!efectivos.some(x=>String(x.codigo)===codigo))return Response.json({error:"driver_not_on_guard"},{status:409});await sql`INSERT INTO guardia_conductores(fecha,codigo,nombre,autorizado_por) VALUES(${fecha}::date,${codigo},${nombre},${of.codigo}) ON CONFLICT(fecha) DO UPDATE SET codigo=EXCLUDED.codigo,nombre=EXCLUDED.nombre,autorizado_por=EXCLUDED.autorizado_por,actualizado_en=now()`;return Response.json({ok:true,conductor:{codigo,nombre},autorizadoPor:of})}catch(e){console.error(e);return Response.json({error:"database_error"},{status:500})}}
