"use client";
import {useEffect,useMemo,useState} from "react";

const pad=n=>String(n).padStart(2,"0");
const isoLocal=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDate=s=>{const [y,m,d]=String(s).slice(0,10).split("-").map(Number);return new Date(y,m-1,d,12)};
const addDays=(s,n)=>{const d=parseDate(s);d.setDate(d.getDate()+n);return isoLocal(d)};
const monthName=d=>d.toLocaleDateString("es-CL",{month:"long",year:"numeric"});
const EASTER={2026:"2026-04-05",2027:"2027-03-28",2028:"2028-04-16",2029:"2029-04-01",2030:"2030-04-21"};
function easterOffset(year,offset){const e=EASTER[year];return e?addDays(e,offset):null}
function feriadoChile(key){const d=parseDate(key),y=d.getFullYear(),md=key.slice(5);const fixed={"01-01":"Año Nuevo","05-01":"Día del Trabajo","05-21":"Glorias Navales","06-20":"Día Nacional de los Pueblos Indígenas","07-16":"Virgen del Carmen","08-15":"Asunción de la Virgen","09-18":"Independencia Nacional","09-19":"Glorias del Ejército","10-31":"Día de las Iglesias Evangélicas y Protestantes","11-01":"Todos los Santos","12-08":"Inmaculada Concepción","12-25":"Navidad"};if(fixed[md])return fixed[md];if(key===easterOffset(y,-2))return"Viernes Santo";if(key===easterOffset(y,-1))return"Sábado Santo";return""}
const COLORS={red:"#c62f2f",gold:"#d5a62e",confirmed:"#6b5a22",open:"#245f36",closed:"#254d73",odd:"#63377b",suspended:"#8b2727",covered:"#a96117",selected:"#8b6d1f"};

export default function CalendarioGuardia(){
 const today=new Date(),[view,setView]=useState(new Date(today.getFullYear(),today.getMonth(),1,12)),[semanas,setSemanas]=useState([]),[estadosNoche,setEstadosNoche]=useState([]),[oficial,setOficial]=useState(""),[inicio,setInicio]=useState(""),[fin,setFin]=useState(""),[apertura,setApertura]=useState(""),[cierre,setCierre]=useState(""),[msg,setMsg]=useState(""),[enlace,setEnlace]=useState("");
 const desde=isoLocal(new Date(view.getFullYear(),view.getMonth()-1,1,12)),hasta=isoLocal(new Date(view.getFullYear(),view.getMonth()+2,0,12));
 async function cargar(){const r=await fetch(`/api/guardia/semanas?desde=${desde}&hasta=${hasta}`,{cache:"no-store"});const j=await r.json();setSemanas(j.semanas||[]);setEstadosNoche(j.estadosNoche||[])}
 useEffect(()=>{cargar()},[view]);
 function elegirDia(key){setInicio(key);setFin(addDays(key,6));setMsg("");setEnlace("")}
 function moverMes(delta){setView(v=>new Date(v.getFullYear(),v.getMonth()+delta,1,12))}
 async function abrir(e){e.preventDefault();setMsg("");const r=await fetch("/api/guardia/semanas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fechaInicio:inicio,fechaFin:fin,apertura,cierre,oficial})});const j=await r.json();setMsg(r.ok?"Período de 7 días confirmado. Ahora puedes abrir la inscripción.":j.error==="period_must_be_7_days"?"La guardia debe comprender exactamente 7 días consecutivos.":j.error||"No fue posible confirmar el período.");if(r.ok){setEnlace("");cargar()}}
 async function estado(w,nuevo){const r=await fetch("/api/guardia/semanas",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fechaInicio:w.fecha_inicio,fechaFin:w.fecha_fin,estado:nuevo,oficial})});if(r.ok)cargar();else setMsg("No fue posible cambiar el estado.")}
 const calendario=useMemo(()=>{const out=[],primero=new Date(view.getFullYear(),view.getMonth(),1,12),offset=(primero.getDay()+6)%7;for(let i=0;i<42;i++){const d=new Date(primero);d.setDate(primero.getDate()-offset+i);const key=isoLocal(d),w=semanas.find(x=>key>=String(x.fecha_inicio).slice(0,10)&&key<=String(x.fecha_fin).slice(0,10)),en=estadosNoche.find(x=>String(x.fecha).slice(0,10)===key);out.push({key,n:d.getDate(),mes:d.getMonth()===primero.getMonth(),estado:en?.estado||w?.estado||"",feriado:feriadoChile(key),seleccionado:inicio&&fin&&key>=inicio&&key<=fin})}return out},[view,semanas,estadosNoche,inicio,fin]);
 const bg=x=>x.seleccionado?COLORS.selected:x.estado==="confirmada"?COLORS.confirmed:x.estado==="abierta"?COLORS.open:x.estado==="suspendida"?COLORS.suspended:x.estado==="cerrada"?COLORS.closed:x.estado==="odd_emitida"?COLORS.odd:x.estado==="cubierta_otra_compania"?COLORS.covered:"#101216";
 const S={input:{width:"100%",boxSizing:"border-box",padding:12,background:"#101216",color:"#fff",border:"1px solid #3a3d44",borderRadius:7},btn:{padding:"11px 14px",background:COLORS.red,color:"#fff",border:0,borderRadius:7,fontWeight:800,cursor:"pointer"},nav:{width:42,height:42,borderRadius:8,border:"1px solid #3a3d44",background:"#101216",color:"#fff",fontSize:22,cursor:"pointer"}};
 return <main style={{minHeight:"100vh",background:"#0d0e11",color:"#f2f2f2",fontFamily:"Arial,sans-serif",padding:14}}><div style={{maxWidth:860,margin:"auto"}}>
 <header style={{background:"#15171b",border:"1px solid #30333a",borderTop:`4px solid ${COLORS.red}`,borderRadius:10,padding:18,marginBottom:12}}><b style={{color:COLORS.gold}}>CUERPO DE BOMBEROS DE VILLARRICA</b><h1 style={{margin:"5px 0",fontSize:22}}>Calendario de Guardia</h1><span>Solo Oficialidad · Apertura de inscripciones</span></header>
 <section style={{background:"#15171b",border:"1px solid #30333a",borderRadius:10,padding:14,marginBottom:12}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:14}}><button type="button" aria-label="Mes anterior" style={S.nav} onClick={()=>moverMes(-1)}>‹</button><div style={{textAlign:"center"}}><b style={{fontSize:20,textTransform:"capitalize"}}>{monthName(view)}</b><div style={{fontSize:12,color:"#aaa"}}>Pulsa el primer día de la Guardia para seleccionar 7 días</div></div><button type="button" aria-label="Mes siguiente" style={S.nav} onClick={()=>moverMes(1)}>›</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(0,1fr))",gap:5,textAlign:"center"}}>{["L","M","X","J","V","S","D"].map(x=><b key={x} style={{color:COLORS.gold,fontSize:12}}>{x}</b>)}{calendario.map(x=><button type="button" key={x.key} onClick={()=>elegirDia(x.key)} title={[x.estado||"Sin semana",x.feriado].filter(Boolean).join(" · ")} style={{minHeight:58,padding:"7px 2px",borderRadius:6,border:x.seleccionado?`2px solid ${COLORS.gold}`:"1px solid #30333a",opacity:x.mes?1:.38,background:bg(x),color:"#fff",cursor:"pointer",position:"relative"}}><b>{x.n}</b>{x.feriado&&<span style={{display:"block",marginTop:3,fontSize:9,lineHeight:1.05,color:"#ffd36b",overflow:"hidden",textOverflow:"ellipsis"}}>{x.feriado}</span>}</button>)}</div><div style={{marginTop:10,fontSize:12,color:"#aaa",lineHeight:1.5}}>Dorado: período confirmado · Verde: inscripción abierta · Azul: cerrada/revisión · Morado: ODD emitida · Rojo: suspendida · Naranjo: cubierta por otra Compañía · Oscuro: sin programación. Los feriados nacionales aparecen identificados dentro del día.</div></section>
 <section style={{background:"#15171b",border:"1px solid #30333a",borderRadius:10,padding:14,marginBottom:12}}><h2 style={{fontSize:17}}>Confirmar los 7 días de Guardia</h2><form onSubmit={abrir} style={{display:"grid",gap:10}}><label>Código oficial<input style={S.input} value={oficial} onChange={e=>setOficial(e.target.value)} required/></label><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}><label>Inicio de semana<input type="date" style={S.input} value={inicio} onChange={e=>{setInicio(e.target.value);if(e.target.value)setFin(addDays(e.target.value,6))}} required/></label><label>Fin de semana<input type="date" style={{...S.input,opacity:.85}} value={fin} readOnly required/></label></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}><label>Apertura<input type="datetime-local" style={S.input} value={apertura} onChange={e=>setApertura(e.target.value)} required/></label><label>Cierre<input type="datetime-local" style={S.input} value={cierre} onChange={e=>setCierre(e.target.value)} required/></label></div><button style={S.btn}>Confirmar período de 7 días</button></form>{msg&&<p>{msg}</p>}{enlace&&<div style={{marginTop:12,padding:12,background:"#101216",border:"1px solid #3a3d44",borderRadius:7}}><small>Enlace de inscripción</small><div style={{wordBreak:"break-all",margin:"6px 0",color:COLORS.gold}}>{enlace}</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button type="button" style={S.btn} onClick={()=>navigator.clipboard?.writeText(enlace)}>Copiar enlace</button><a style={{...S.btn,textDecoration:"none"}} href={`https://wa.me/?text=${encodeURIComponent("Inscripción Guardia Nocturna: "+enlace)}`} target="_blank" rel="noreferrer">Compartir por WhatsApp</a></div></div>}</section>
 <section style={{background:"#15171b",border:"1px solid #30333a",borderRadius:10,padding:14}}><h2 style={{fontSize:17,marginTop:0}}>Semanas programadas</h2>{semanas.length===0?<p>No hay semanas creadas en este período.</p>:semanas.map(w=><div key={w.id} style={{padding:12,margin:"8px 0",border:"1px solid #3a3d44",borderRadius:8}}><b>{String(w.fecha_inicio).slice(0,10)} → {String(w.fecha_fin).slice(0,10)}</b><div style={{color:COLORS.gold,margin:"5px 0"}}>{String(w.estado).toUpperCase()}</div><small>Apertura: {new Date(w.apertura).toLocaleString("es-CL")} · Cierre: {new Date(w.cierre).toLocaleString("es-CL")}</small><div style={{display:"flex",gap:7,marginTop:9,flexWrap:"wrap"}}><button style={S.btn} onClick={()=>{estado(w,"abierta");setEnlace(`${window.location.origin}/guardia?inicio=${String(w.fecha_inicio).slice(0,10)}`)}}>Abrir inscripción</button><button style={S.btn} onClick={()=>estado(w,"cerrada")}>Cerrar</button><button style={S.btn} onClick={()=>estado(w,"suspendida")}>Suspender</button></div></div>)}</section>
 </div></main>
}