"use client";
import {useEffect,useState} from "react";
const iso=d=>d.toISOString().slice(0,10);
export default function CalendarioGuardia(){
 const now=new Date(), [desde,setDesde]=useState(iso(new Date(now.getFullYear(),now.getMonth(),1))),[hasta,setHasta]=useState(iso(new Date(now.getFullYear(),now.getMonth()+2,0))),[semanas,setSemanas]=useState([]),[estadosNoche,setEstadosNoche]=useState([]),[oficial,setOficial]=useState(""),[inicio,setInicio]=useState(""),[fin,setFin]=useState(""),[apertura,setApertura]=useState(""),[cierre,setCierre]=useState(""),[msg,setMsg]=useState(""),[enlace,setEnlace]=useState("");
 async function cargar(){const r=await fetch(`/api/guardia/semanas?desde=${desde}&hasta=${hasta}`,{cache:"no-store"});const j=await r.json();setSemanas(j.semanas||[]);setEstadosNoche(j.estadosNoche||[])}
 useEffect(()=>{cargar()},[]);
 async function abrir(e){e.preventDefault();setMsg("");const r=await fetch("/api/guardia/semanas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fechaInicio:inicio,fechaFin:fin,apertura,cierre,oficial})});const j=await r.json();setMsg(r.ok?"Semana creada y abierta.":j.error||"No fue posible abrir la semana.");if(r.ok){setEnlace(`${window.location.origin}/guardia?inicio=${inicio}`);cargar()}}
 async function estado(w,estado){const r=await fetch("/api/guardia/semanas",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fechaInicio:w.fecha_inicio,fechaFin:w.fecha_fin,estado,oficial})});if(r.ok)cargar();else setMsg("No fue posible cambiar el estado.")}
 const calendario=[];const base=new Date(desde+"T12:00:00"),primero=new Date(base.getFullYear(),base.getMonth(),1,12);const offset=(primero.getDay()+6)%7;for(let i=0;i<42;i++){const d=new Date(primero);d.setDate(primero.getDate()-offset+i);const key=iso(d),w=semanas.find(x=>key>=String(x.fecha_inicio).slice(0,10)&&key<=String(x.fecha_fin).slice(0,10));const en=estadosNoche.find(x=>String(x.fecha).slice(0,10)===key);calendario.push({key,n:d.getDate(),mes:d.getMonth()===primero.getMonth(),estado:en?.estado||w?.estado||""})}
 const S={input:{width:"100%",padding:12,background:"#101216",color:"#fff",border:"1px solid #3a3d44",borderRadius:7},btn:{padding:"11px 14px",background:"#ef5d73",color:"#fff",border:0,borderRadius:7,fontWeight:800,cursor:"pointer"}};
 return <main style={{minHeight:"100vh",background:"#0d0e11",color:"#f2f2f2",fontFamily:"Arial,sans-serif",padding:14}}><div style={{maxWidth:760,margin:"auto"}}>
 <header style={{background:"#15171b",border:"1px solid #30333a",borderTop:"4px solid #ef5d73",borderRadius:10,padding:18,marginBottom:12}}><b style={{color:"#d5a62e"}}>CUERPO DE BOMBEROS DE VILLARRICA</b><h1 style={{margin:"5px 0",fontSize:22}}>Calendario de Guardia</h1><span>Solo Oficialidad · Apertura de inscripciones</span></header>
 <section style={{background:"#15171b",border:"1px solid #30333a",borderRadius:10,padding:14,marginBottom:12}}><div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:5,textAlign:"center"}}>{["L","M","X","J","V","S","D"].map(x=><b key={x} style={{color:"#d5a62e",fontSize:12}}>{x}</b>)}{calendario.map(x=><div key={x.key} title={x.estado||"Sin semana"} style={{padding:"10px 2px",borderRadius:6,border:"1px solid #30333a",opacity:x.mes?1:.35,background:x.estado==="abierta"?"#284f35":x.estado==="suspendida"?"#6d2428":x.estado==="cerrada"?"#29486d":x.estado==="odd_emitida"?"#5a3472":x.estado==="cubierta_otra_compania"?"#9a5a19":"#101216"}}><b>{x.n}</b></div>)}</div><div style={{marginTop:10,fontSize:12,color:"#aaa"}}>Verde: inscripción abierta · Azul: cerrada / revisión · Morado: ODD emitida · Rojo: suspendida · Naranjo: cubierta por otra Compañía · Oscuro: sin programación</div></section>
 <section style={{background:"#15171b",border:"1px solid #30333a",borderRadius:10,padding:14,marginBottom:12}}><h2 style={{fontSize:17}}>Crear semana y abrir inscripción</h2><form onSubmit={abrir} style={{display:"grid",gap:10}}><label>Código oficial<input style={S.input} value={oficial} onChange={e=>setOficial(e.target.value)} required/></label><label>Inicio de semana<input type="date" style={S.input} value={inicio} onChange={e=>setInicio(e.target.value)} required/></label><label>Fin de semana<input type="date" style={S.input} value={fin} onChange={e=>setFin(e.target.value)} required/></label><label>Apertura<input type="datetime-local" style={S.input} value={apertura} onChange={e=>setApertura(e.target.value)} required/></label><label>Cierre<input type="datetime-local" style={S.input} value={cierre} onChange={e=>setCierre(e.target.value)} required/></label><button style={S.btn}>Crear semana y abrir inscripción</button></form>{msg&&<p>{msg}</p>}{enlace&&<div style={{marginTop:12,padding:12,background:"#101216",border:"1px solid #3a3d44",borderRadius:7}}><small>Enlace de inscripción</small><div style={{wordBreak:"break-all",margin:"6px 0",color:"#d5a62e"}}>{enlace}</div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button type="button" style={S.btn} onClick={()=>navigator.clipboard?.writeText(enlace)}>Copiar enlace</button><a style={{...S.btn,textDecoration:"none"}} href={`https://wa.me/?text=${encodeURIComponent("Inscripción Guardia Nocturna: "+enlace)}`} target="_blank" rel="noreferrer">Compartir por WhatsApp</a></div></div>}</section>
 <section style={{background:"#15171b",border:"1px solid #30333a",borderRadius:10,padding:14}}><div style={{display:"flex",gap:8,marginBottom:12}}><input type="date" style={S.input} value={desde} onChange={e=>setDesde(e.target.value)}/><input type="date" style={S.input} value={hasta} onChange={e=>setHasta(e.target.value)}/><button style={S.btn} onClick={cargar}>Actualizar</button></div>
 {semanas.length===0?<p>No hay semanas creadas en este período.</p>:semanas.map(w=><div key={w.id} style={{padding:12,margin:"8px 0",border:"1px solid #3a3d44",borderRadius:8}}><b>{w.fecha_inicio} → {w.fecha_fin}</b><div style={{color:"#d5a62e",margin:"5px 0"}}>{String(w.estado).toUpperCase()}</div><small>Apertura: {new Date(w.apertura).toLocaleString("es-CL")} · Cierre: {new Date(w.cierre).toLocaleString("es-CL")}</small><div style={{display:"flex",gap:7,marginTop:9,flexWrap:"wrap"}}><button style={S.btn} onClick={()=>estado(w,"abierta")}>Abrir</button><button style={S.btn} onClick={()=>estado(w,"cerrada")}>Cerrar</button><button style={S.btn} onClick={()=>estado(w,"suspendida")}>Suspender</button></div></div>)}</section>
 </div></main>
}