"use client";
import {useEffect,useMemo,useState} from "react";

const pad=n=>String(n).padStart(2,"0");
const isoLocal=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parse=s=>new Date(`${String(s).slice(0,10)}T12:00:00`);
const addDays=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return isoLocal(d)};
const monthName=d=>new Intl.DateTimeFormat("es-CL",{month:"long",year:"numeric"}).format(d);
const COLORS={confirmada:"#6b5a22",abierta:"#284f35",cerrada:"#29486d",revision:"#29486d",odd_emitida:"#5a3472",suspendida:"#7b1f1f",cubierta_otra_compania:"#9a5a19"};
const FERIADOS_2026={
 "2026-01-01":"Año Nuevo","2026-04-03":"Viernes Santo","2026-04-04":"Sábado Santo","2026-05-01":"Día Nacional del Trabajo","2026-05-21":"Día de las Glorias Navales","2026-06-21":"Día Nacional de los Pueblos Indígenas","2026-06-29":"San Pedro y San Pablo","2026-07-16":"Día de la Virgen del Carmen","2026-08-15":"Asunción de la Virgen","2026-09-18":"Independencia Nacional","2026-09-19":"Día de las Glorias del Ejército","2026-10-12":"Encuentro de Dos Mundos","2026-10-31":"Día de las Iglesias Evangélicas y Protestantes","2026-11-01":"Día de Todos los Santos","2026-12-08":"Inmaculada Concepción","2026-12-25":"Navidad"
};

export default function CalendarioGuardia(){
 const hoy=new Date();
 const [mes,setMes]=useState(new Date(hoy.getFullYear(),hoy.getMonth(),1,12));
 const [semanas,setSemanas]=useState([]),[estadosNoche,setEstadosNoche]=useState([]);
 const [oficial,setOficial]=useState(""),[inicio,setInicio]=useState(""),[fin,setFin]=useState(""),[apertura,setApertura]=useState(""),[cierre,setCierre]=useState(""),[msg,setMsg]=useState(""),[enlace,setEnlace]=useState("");
 const desde=isoLocal(new Date(mes.getFullYear(),mes.getMonth()-1,1,12));
 const hasta=isoLocal(new Date(mes.getFullYear(),mes.getMonth()+2,0,12));
 async function cargar(){try{const r=await fetch(`/api/guardia/semanas?desde=${desde}&hasta=${hasta}`,{cache:"no-store"});const j=await r.json();setSemanas(j.semanas||[]);setEstadosNoche(j.estadosNoche||[])}catch{setMsg("No fue posible cargar el calendario.")}}
 useEffect(()=>{cargar()},[mes]);
 function seleccionarDia(key){setInicio(key);setFin(addDays(key,6));setMsg("")}
 async function confirmar(e){e.preventDefault();setMsg("");if(!inicio||fin!==addDays(inicio,6)){setMsg("Selecciona el primer día de la Guardia. El sistema marcará automáticamente los 7 días.");return}const r=await fetch("/api/guardia/semanas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fechaInicio:inicio,fechaFin:fin,apertura,cierre,oficial})});const j=await r.json();setMsg(r.ok?"Período de 7 días confirmado.":j.error==="period_must_be_7_days"?"La guardia debe comprender exactamente 7 días consecutivos.":j.error||"No fue posible confirmar el período.");if(r.ok){setEnlace("");cargar()}}
 async function estado(w,nuevo){const r=await fetch("/api/guardia/semanas",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fechaInicio:w.fecha_inicio,fechaFin:w.fecha_fin,estado:nuevo,oficial})});if(r.ok)cargar();else setMsg("No fue posible cambiar el estado.")}
 const calendario=useMemo(()=>{const out=[],primero=new Date(mes.getFullYear(),mes.getMonth(),1,12),offset=(primero.getDay()+6)%7;for(let i=0;i<42;i++){const d=new Date(primero);d.setDate(primero.getDate()-offset+i);const key=isoLocal(d),w=semanas.find(x=>key>=String(x.fecha_inicio).slice(0,10)&&key<=String(x.fecha_fin).slice(0,10)),en=estadosNoche.find(x=>String(x.fecha).slice(0,10)===key);out.push({key,n:d.getDate(),mes:d.getMonth()===primero.getMonth(),estado:en?.estado||w?.estado||"",feriado:FERIADOS_2026[key]||"",seleccionado:inicio&&key>=inicio&&key<=fin})}return out},[mes,semanas,estadosNoche,inicio,fin]);
 const S={input:{width:"100%",boxSizing:"border-box",padding:12,background:"#100d0b",color:"#f2eadf",border:"1px solid #493a31",borderRadius:5},btn:{padding:"11px 14px",background:"#b3241c",color:"#fff",border:"1px solid #d23a2f",borderRadius:5,fontWeight:800,cursor:"pointer"},secondary:{padding:"9px 12px",background:"#17110e",color:"#d5a62e",border:"1px solid #493a31",borderRadius:5,fontWeight:800,cursor:"pointer"}};
 return <main style={{minHeight:"100vh",background:"#100c0a",color:"#eee5da",fontFamily:"Arial,sans-serif",padding:14}}><div style={{maxWidth:900,margin:"auto"}}>
 <header style={{background:"#18120f",border:"1px solid #493a31",borderTop:"4px solid #b3241c",borderRadius:8,padding:18,marginBottom:12}}><b style={{color:"#d5a62e"}}>CUERPO DE BOMBEROS DE VILLARRICA</b><h1 style={{margin:"5px 0",fontSize:24}}>Calendario de Guardia</h1><span>Solo Oficialidad · Apertura de inscripciones</span></header>
 <section style={{background:"#18120f",border:"1px solid #493a31",borderRadius:8,padding:14,marginBottom:12}}>
 <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8,marginBottom:14}}><button type="button" style={S.secondary} onClick={()=>setMes(new Date(mes.getFullYear(),mes.getMonth()-1,1,12))}>‹ Anterior</button><strong style={{textTransform:"capitalize",fontSize:18,color:"#d5a62e"}}>{monthName(mes)}</strong><div style={{display:"flex",gap:6}}><button type="button" style={S.secondary} onClick={()=>setMes(new Date(hoy.getFullYear(),hoy.getMonth(),1,12))}>Hoy</button><button type="button" style={S.secondary} onClick={()=>setMes(new Date(mes.getFullYear(),mes.getMonth()+1,1,12))}>Siguiente ›</button></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:5,textAlign:"center"}}>{["L","M","X","J","V","S","D"].map(x=><b key={x} style={{color:"#d5a62e",fontSize:12}}>{x}</b>)}{calendario.map(x=><button type="button" key={x.key} onClick={()=>seleccionarDia(x.key)} title={x.feriado||x.estado||"Seleccionar inicio de Guardia"} style={{minHeight:52,padding:"6px 2px",borderRadius:5,border:x.seleccionado?"2px solid #d5a62e":"1px solid #493a31",opacity:x.mes?1:.35,background:x.seleccionado?"#4b3b17":COLORS[x.estado]||"#100d0b",color:"#fff",cursor:"pointer"}}><b>{x.n}</b>{x.feriado&&<small style={{display:"block",marginTop:3,color:"#e1b94e",fontSize:9,lineHeight:1.05}}>FERIADO</small>}</button>)}</div>
 <div style={{marginTop:10,fontSize:12,color:"#b9aa9d"}}>Pulsa el primer día de la Guardia: se marcarán automáticamente 7 días. Dorado: confirmado · Verde: inscripción abierta · Azul: cerrada/revisión · Morado: ODD emitida · Rojo: suspendida · Naranjo: cubierta por otra Compañía.</div>
 {calendario.filter(x=>x.mes&&x.feriado).length>0&&<div style={{marginTop:8,fontSize:12,color:"#d5a62e"}}>{calendario.filter(x=>x.mes&&x.feriado).map(x=><div key={x.key}>{x.key}: {x.feriado}</div>)}</div>}
 </section>
 <section style={{background:"#18120f",border:"1px solid #493a31",borderRadius:8,padding:14,marginBottom:12}}><h2 style={{fontSize:17}}>Confirmar los 7 días de Guardia</h2><form onSubmit={confirmar} style={{display:"grid",gap:10}}><label>Código oficial<input style={S.input} value={oficial} onChange={e=>setOficial(e.target.value)} required/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><label>Inicio<input type="date" style={S.input} value={inicio} onChange={e=>{setInicio(e.target.value);setFin(e.target.value?addDays(e.target.value,6):"")}} required/></label><label>Fin automático<input type="date" style={S.input} value={fin} readOnly required/></label></div><label>Apertura de inscripción<input type="datetime-local" style={S.input} value={apertura} onChange={e=>setApertura(e.target.value)} required/></label><label>Cierre de inscripción<input type="datetime-local" style={S.input} value={cierre} onChange={e=>setCierre(e.target.value)} required/></label><button style={S.btn}>Confirmar período de 7 días</button></form>{msg&&<p style={{color:"#e1b94e"}}>{msg}</p>}{enlace&&<div style={{marginTop:12,padding:12,background:"#100d0b",border:"1px solid #493a31",borderRadius:7}}><small>Enlace de inscripción</small><div style={{wordBreak:"break-all",margin:"6px 0",color:"#d5a62e"}}>{enlace}</div></div>}</section>
 <section style={{background:"#18120f",border:"1px solid #493a31",borderRadius:8,padding:14}}><h2 style={{fontSize:17}}>Semanas programadas</h2>{semanas.length===0?<p>No hay semanas creadas en este período.</p>:semanas.map(w=><div key={w.id} style={{padding:12,margin:"8px 0",border:"1px solid #493a31",borderRadius:6}}><b>{String(w.fecha_inicio).slice(0,10)} → {String(w.fecha_fin).slice(0,10)}</b><div style={{color:"#d5a62e",margin:"5px 0"}}>{String(w.estado).toUpperCase()}</div><small>Apertura: {new Date(w.apertura).toLocaleString("es-CL")} · Cierre: {new Date(w.cierre).toLocaleString("es-CL")}</small><div style={{display:"flex",gap:7,marginTop:9,flexWrap:"wrap"}}><button style={S.btn} onClick={()=>{estado(w,"abierta");setEnlace(`${window.location.origin}/guardia?inicio=${String(w.fecha_inicio).slice(0,10)}`)}}>Abrir inscripción</button><button style={S.btn} onClick={()=>estado(w,"cerrada")}>Cerrar</button><button style={S.btn} onClick={()=>estado(w,"suspendida")}>Suspender</button></div></div>)}</section>
 </div></main>
}