"use client";
import {useMemo,useState} from "react";
import "./odd.css";
const TYPES=[["citacion","Citación / Academia / Ejercicio"],["guardia","Guardia Nocturna"],["nomina","Nómina y Claves"],["disposicion","Disposición General"]];
const today=new Date().toISOString().slice(0,10);
export default function Page(){
 const[type,setType]=useState("citacion");
 const[f,setF]=useState({year:new Date().getFullYear(),number:"",issueDate:today,title:"",eventDate:"",time:"20:00",place:"Cuartel General, Valentín Letelier #630",activity:"Academia",topic:"",clothing:"Civil",punctuality:"Se exige PUNTUALIDAD",excuses:"germaniacbv@gmail.com",recipients:"Quinta Compañía",seen:"",considering:"",provisions:"",notes:""});
 const set=(k,v)=>setF(x=>({...x,[k]:v})); const odd=useMemo(()=>String(f.number||"___").padStart(3,"0")+"/"+f.year,[f.number,f.year]);
 return <main className="oddShell"><header className="oddTop"><div><b>GERMANIA</b><span> · ODD Maestras</span></div><a href="/">Volver a GERMANIA</a></header>
 <section className="oddIntro"><h1>Generar Orden del Día</h1><p>Selecciona una plantilla. Solo aparecen los campos necesarios y la vista previa cambia en vivo.</p></section>
 <nav className="oddTypes">{TYPES.map(([id,label])=><button key={id} onClick={()=>setType(id)} className={type===id?"active":""}>{label}</button>)}</nav>
 <div className="oddGrid"><section className="oddForm card">
 <div className="row"><Field label="Año"><input type="number" value={f.year} onChange={e=>set("year",e.target.value)}/></Field><Field label="Nº ODD"><input inputMode="numeric" value={f.number} onChange={e=>set("number",e.target.value)}/></Field><Field label="Fecha emisión"><input type="date" value={f.issueDate} onChange={e=>set("issueDate",e.target.value)}/></Field></div>
 <Field label="Asunto / título"><input value={f.title} onChange={e=>set("title",e.target.value)} placeholder="Ej.: Academia · Estabilización vehicular"/></Field>
 {type==="citacion"&&<><div className="row"><Field label="Fecha actividad"><input type="date" value={f.eventDate} onChange={e=>set("eventDate",e.target.value)}/></Field><Field label="Hora"><input type="time" value={f.time} onChange={e=>set("time",e.target.value)}/></Field></div><Field label="Lugar"><input value={f.place} onChange={e=>set("place",e.target.value)}/></Field><div className="row"><Field label="Actividad"><select value={f.activity} onChange={e=>set("activity",e.target.value)}><option>Academia</option><option>Ejercicio</option><option>Capacitación</option><option>Ceremonia / formación</option></select></Field><Field label="Tema"><input value={f.topic} onChange={e=>set("topic",e.target.value)}/></Field></div><Field label="Vestimenta"><input value={f.clothing} onChange={e=>set("clothing",e.target.value)}/></Field><div className="row"><Field label="Puntualidad"><input value={f.punctuality} onChange={e=>set("punctuality",e.target.value)}/></Field><Field label="Excusas al correo"><input type="email" value={f.excuses} onChange={e=>set("excuses",e.target.value)}/></Field></div></>}
 {type==="guardia"&&<><Field label="Período / instrucciones"><textarea rows={7} value={f.notes} onChange={e=>set("notes",e.target.value)} placeholder="Período, horarios, dotación mínima e instrucciones generales"/></Field><p className="hint">Preparado para conectar fecha, OBAC, conductor/maquinista y voluntarios con Guardia.</p></>}
 {type==="nomina"&&<><p className="hint">Tomará automáticamente desde GERMANIA: clave, nombre, apellidos, RUT, cargo y teléfono.</p><Field label="Observación / vigencia"><textarea rows={4} value={f.notes} onChange={e=>set("notes",e.target.value)}/></Field></>}
 {type==="disposicion"&&<><Field label="VISTOS"><textarea rows={4} value={f.seen} onChange={e=>set("seen",e.target.value)}/></Field><Field label="CONSIDERANDO"><textarea rows={4} value={f.considering} onChange={e=>set("considering",e.target.value)}/></Field><Field label="SE DISPONE"><textarea rows={7} value={f.provisions} onChange={e=>set("provisions",e.target.value)} placeholder={"1. ...\n2. ..."}/></Field></>}
 <Field label="Distribución / destinatarios"><input value={f.recipients} onChange={e=>set("recipients",e.target.value)}/></Field>
 <div className="actions"><button>Guardar borrador</button><button className="primary">Emitir y archivar</button><button>↓ Descargar PDF</button><button>Compartir</button><button>Correo institucional</button></div><p className="hint">Módulo aislado de prueba: todavía no modifica la base maestra.</p>
 </section><aside className="preview card"><div className="paper"><div className="paperHead"><img src="/legacy/germania-icon.png" alt="Emblema Germania"/><div><b>Quinta Compañía de Bomberos “Germania” de Villarrica</b><small>Cuartel General · Valentín Letelier #630 · Villarrica</small><small>germaniacbv@gmail.com</small></div></div><div className="flag"></div><p className="date">Villarrica · {f.issueDate||"fecha"}</p><h2>Orden del Día {odd}</h2>{f.title&&<h3>{f.title}</h3>}
 {type==="citacion"&&<div className="docText"><p>Por orden del Capitán de Compañía, cítese a la Quinta Compañía.</p><p><b>Fecha:</b> {f.eventDate||"—"} · <b>Hora:</b> {f.time||"—"} hrs.</p><p><b>Lugar:</b> {f.place||"—"}</p><p><b>Actividad:</b> {f.activity||"—"}</p><p><b>Tema:</b> {f.topic||"—"}</p><p><b>Vestimenta:</b> {f.clothing||"—"}</p><p className="strong">{f.punctuality}</p><p>Excusas al correo {f.excuses}</p></div>}
 {type==="guardia"&&<div className="docText"><h4>GUARDIA NOCTURNA</h4><p>{f.notes||"Complete período, horarios, dotación e instrucciones."}</p><div className="mockTable">ANEXO · Programación diaria de Guardia</div></div>}
 {type==="nomina"&&<div className="docText"><h4>NÓMINA Y CLAVES</h4><div className="mockTable">CLAVE · NOMBRE · APELLIDOS · RUT · CARGO · TELÉFONO</div><p>{f.notes}</p></div>}
 {type==="disposicion"&&<div className="docText"><h4>VISTOS:</h4><p>{f.seen||"—"}</p><h4>CONSIDERANDO:</h4><p>{f.considering||"—"}</p><h4>SE DISPONE:</h4><p className="pre">{f.provisions||"—"}</p></div>}
 <p className="closing">Tómese razón, distribúyase por medio del correo electrónico institucional, léase y archívese.</p><div className="sign"><span>CAPITÁN</span><span>AYUDANTE</span></div></div></aside></div></main>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
